args:
  - { name: sens, value: "0.105" }
hits:
  - 30
stable:
  - { pixel: 3, delay: 28 }
keys:
  - { code: SCRCPY_FIRE, point: { x: 324, y: 113 }, comment: "开火键" }
  - { code: SCRCPY_VISION_TOPLEFT, point: { x: 650, y: 100 }, comment: "视野滑动事件左上坐标" }
  - { code: SCRCPY_VISION_BOTTOMRIGHT, point: { x: 1200, y: 850 }, comment: "视野滑动事件右下坐标" }
  - { code: SCRCPY_FRONT, point: { x: 380, y: 919 }, comment: "方向键 前" }
  - { code: SCRCPY_BACK, point: { x: 380, y: 1232 }, comment: "方向键 后" }
  - { code: Space, point: { x: 2246, y: 761 }, comment: "跳/紧急停车" }
  - { code: C, point: { x: 2239, y: 554 }, comment: "趴/下车" }
  - { code: "Left Shift", point: { x: 2020, y: 1108 }, comment: "蹲/加速/下沉" }
  - { code: R, point: { x: 1882, y: 1350 }, comment: "换弹/投掷距离切换" }
  - { code: E, point: { x: 2397, y: 986 }, comment: "准镜/喇叭" }
  - { code: Q, point: { x: 420, y: 520 }, comment: "左摆头" }
  - { code: Z, point: { x: 2037, y: 867 }, comment: "救人/上浮" }
  - { code: T, point: { x: 1645, y: 368 }, comment: "舔包" }
  - { code: Y, point: { x: 1768, y: 371 }, comment: "打开/收起拾取列表" }
  - { code: F, point: { x: 1596, y: 514 }, comment: "拾取物品1" }
  - { code: G, point: { x: 1596, y: 652 }, comment: "拾取物品2" }
  - { code: H, point: { x: 1596, y: 787 }, comment: "拾取物品3" }
  - { code: J, point: { x: 1596, y: 892 }, comment: "拾取物品4" }
  - { code: V, point: { x: 1670, y: 992 }, comment: "开/关门" }
  - { code: "1", point: { x: 1109, y: 1305 }, comment: "1号武器" }
  - { code: "2", point: { x: 1455, y: 1305 }, comment: "2号武器" }
  - { code: "3", point: { x: 796, y: 1343 }, comment: "使用医疗物品" }
  - { code: "4", point: { x: 1761, y: 1341 }, comment: "使用投掷物品" }
  - { code: "5", point: { x: 793, y: 1229 }, comment: "打开医疗物品列表" }
  - { code: "6", point: { x: 1759, y: 1223 }, comment: "打开投掷物品列表" }
  - { code: "7", point: { x: 1562, y: 1200 }, comment: "副武器" }
  - { code: B, point: { x: 1091, y: 1211 }, comment: "1号武器单发" }
  - { code: N, point: { x: 1440, y: 1207 }, comment: "2号武器单发" }
  - { code: Tab, point: { x: 62, y: 1337 }, show_pointer: true, comment: "背包列表" }
  - { code: M, point: { x: 2408, y: 76 }, show_pointer: true, comment: "地图" }
  - { code: X, point: { x: 2414, y: 594 }, comment: "打开准镜列表" }
  - { code: ",", point: { x: 2414, y: 353 }, comment: "比例尺放大" }
  - { code: ".", point: { x: 2417, y: 1095 }, comment: "比例尺缩小" }
  - { code: "/", point: { x: 2253, y: 1363 }, comment: "人物置中（地图）" }
  - { code: "'", point: { x: 1721, y: 1368 }, comment: "取消标记点" }
  - { code: "`", point: { x: 829, y: 755 }, comment: "取消投掷" }
  - { code: K, macro: [ { point: { x: 860, y: 292 }, delay: 100 }, { point: { x: 863, y: 811 }, delay: 30 }, { point: { x: 860, y: 292 }, delay: 0 } ], comment: "准镜比例缩小" }
  - { code: L, macro: [ { point: { x: 860, y: 292 }, delay: 100 }, { point: { x: 860, y: 436 }, delay: 30 }, { point: { x: 860, y: 292 }, delay: 0 } ], comment: "准镜比例放大" }
  - { code: U, macro: [ { point: { x: 2414, y: 480 }, delay: 100 }, { point: { x: 2054, y: 203 }, delay: 0 } ], comment: "语音：前方有敌人" }
  - { code: I, macro: [ { point: { x: 2419, y: 482 }, delay: 100 }, { point: { x: 2086, y: 317 }, delay: 0 } ], comment: "语音：我这有物资" }
  - { code: "[", macro: [ { point: { x: 1748, y: 197 }, delay: 100 }, { point: { x: 1577, y: 164 }, delay: 0 } ], comment: "打开团队语音（发出声音）" }
  - { code: "]", macro: [ { point: { x: 1752, y: 203 }, delay: 100 }, { point: { x: 1654, y: 162 }, delay: 0 } ], comment: "关闭团队语音（发出声音）" }
  - { code: "1", type: ctrl, point: { x: 1794, y: 457 }, comment: "准镜切换1" }
  - { code: "2", type: ctrl, point: { x: 1868, y: 460 }, comment: "准镜切换2" }
  - { code: "3", type: ctrl, point: { x: 1755, y: 576 }, comment: "准镜切换3" }
  - { code: "4", type: ctrl, point: { x: 1855, y: 573 }, comment: "准镜切换4" }
  - { code: "5", type: ctrl, point: { x: 1759, y: 695 }, comment: "准镜切换5" }
  - { code: "6", type: ctrl, point: { x: 1878, y: 692 }, comment: "准镜切换6" }
  - { code: "7", type: ctrl, point: { x: 1755, y: 811 }, comment: "准镜切换7" }
  - { code: "[", type: ctrl, macro: [ { point: { x: 1748, y: 115 }, delay: 100 }, { point: { x: 1546, y: 133 }, delay: 0 } ], comment: "打开团队语音（接收声音）" }
  - { code: "]", type: ctrl, macro: [ { point: { x: 1755, y: 123 }, delay: 100 }, { point: { x: 1616, y: 131 }, delay: 0 } ], comment: "关闭团队语音（接收声音）" }
  - { code: BUTTON_RIGHT, type: mouse, point: { x: 632, y: 520 }, comment: "右摆头" }
